# syntax = edrevo/dockerfile-plus

FROM arm32v7/alpine:3.13 AS robotv-build

INCLUDE+ docker/includes/cpu.arm32v7
INCLUDE+ docker/includes/robotv.build

FROM arm32v7/alpine:3.13 AS robotv

INCLUDE+ docker/includes/cpu.arm32v7
INCLUDE+ docker/includes/robotv.env
INCLUDE+ docker/includes/robotv.image
