# syntax = edrevo/dockerfile-plus

FROM arm64v8/alpine:3.13 AS robotv-build

INCLUDE+ docker/includes/cpu.arm64v8
INCLUDE+ docker/includes/robotv.build

FROM arm64v8/alpine:3.13 AS robotv

INCLUDE+ docker/includes/cpu.arm64v8
INCLUDE+ docker/includes/robotv.env
INCLUDE+ docker/includes/robotv.image
